### ISSUE TITLE
* [ERROR] Error occurred parsing the file path: LFI_Wordlists/****

### ISSUE THREAD

**Issue by lekosbelas** [ngimb64/LFI-Chef#1]
(base) **** LFI-Chef % python3 lfi_chef.py --encoding udbo lfi.payload.txt sanitize linux

* [ERROR] Error occurred parsing the file path: lfi.payload.txt *

(base) **** LFI-Chef % python3 lfi_chef.py --encoding udbo LFI_Wordlists/linux_lfi sanitize linux 

* [ERROR] Error occurred parsing the file path: LFI_Wordlists/linux_lfi *

(base) **** LFI-Chef % python3 lfi_chef.py LFI_Wordlists/linux_lfi sanitize linux 

* [ERROR] Error occurred parsing the file path: LFI_Wordlists/linux_lfi *

**Comment by TheBugFather** [comment]
Hello, I'm almost certain the problem you are having is due to improper file path format. Best fix would be to use a relative file path, so for example, LFI_Wordlists/linux_lfi would need to be changed to ./LFI_Wordlists/linux_lfi otherwise it is unable to find the file. This is demonstrated in the screenshot displayed in the base of the repository.
